config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :change_requests
    resources :websites

    root to: "users#index"
  end

  resources :change_requests
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/change_request.rb
class ChangeRequest < ApplicationRecord
  belongs_to :user
  belongs_to :website
  has_secure_token
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  attr_encrypted :security_phrase, :key => '04e7wkTFliZVDBUYIhWfHLuAyzZFEm6N'

  has_many :change_requests
  has_many :websites

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/website.rb
class Website < ApplicationRecord
  belongs_to :user
  has_secure_token
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_admin

    def authenticate_admin
      # TODO Add authentication logic here.
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/change_requests_controller.rb
module Admin
  class ChangeRequestsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = ChangeRequest.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   ChangeRequest.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/websites_controller.rb
module Admin
  class WebsitesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Website.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Website.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/change_requests_controller.rb
class ChangeRequestsController < ApplicationController
  before_action :set_change_request, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /change_requests
  # GET /change_requests.json
  def index
    @change_requests = ChangeRequest.all
  end

  # GET /change_requests/1
  # GET /change_requests/1.json
  def show
  end

  # GET /change_requests/new
  def new
    @change_request = current_user.change_requests.new
  end

  # GET /change_requests/1/edit
  def edit
  end

  # POST /change_requests
  # POST /change_requests.json
  def create
    @change_request = current_user.change_requests.new(change_request_params)

    respond_to do |format|
      if @change_request.save
        format.html { redirect_to @change_request, notice: 'Change request was successfully created.' }
        format.json { render :show, status: :created, location: @change_request }
      else
        format.html { render :new }
        format.json { render json: @change_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /change_requests/1
  # PATCH/PUT /change_requests/1.json
  def update
    respond_to do |format|
      if @change_request.update(change_request_params)
        format.html { redirect_to @change_request, notice: 'Change request was successfully updated.' }
        format.json { render :show, status: :ok, location: @change_request }
      else
        format.html { render :edit }
        format.json { render json: @change_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /change_requests/1
  # DELETE /change_requests/1.json
  def destroy
    @change_request.destroy
    respond_to do |format|
      format.html { redirect_to change_requests_url, notice: 'Change request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_change_request
      @change_request = ChangeRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def change_request_params
      params.require(:change_request).permit(:token, :user_id, :old_content, :new_content, :details, :urgent,
                                            :website_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/change_requests_helper.rb
module ChangeRequestsHelper
end

app/views/change_requests/_form.html.slim
= simple_form_for @change_request do |f|
  - if @change_request.errors.any?
    #error_explanation
      h2 = "#{pluralize(@change_request.errors.count, "error")} prohibited this change_request from being saved:"
      ul
        - @change_request.errors.full_messages.each do |message|
          li = message

  .field
    = f.association :website, collection: current_user.websites
  .field
    = f.input :old_content
  .field
    = f.input :new_content
  .field
    = f.input :details
  .field
    = f.input :urgent, label: 'Check the box if this is urgent'
  .actions = f.submit

app/views/change_requests/edit.html.slim
h1 Editing change_request

== render 'form'

= link_to 'Show', @change_request
'  |
= link_to 'Back', change_requests_path

app/views/change_requests/index.html.slim
- content_for(:site_page_title, 'Request Changes')
h1 Your Change Requests
table.table.table-sm.table-bordered.table-striped
  thead
    tr
      th Details
      th Urgent
      th
      th

  tbody
    - @change_requests.each do |change_request|
      tr
        td = change_request.details
        td = change_request.urgent
        td = link_to 'Show', change_request
        td = link_to 'Edit', edit_change_request_path(change_request)

br

= link_to 'New Change request', new_change_request_path

app/views/change_requests/new.html.slim
h1 New change_request

== render 'form'

= link_to 'Back', change_requests_path

app/views/change_requests/show.html.slim
h2 
  | Change Request <small>#{@change_request.token}</small>

p
  strong User:
  = @change_request.user.email
.row
  .col-md-6
    hr
    p
      strong Old content:
      = @change_request.old_content
    hr
  .col-md-6
    hr
    p
      strong New content:
      = @change_request.new_content
    hr
p
  strong Details:
  = @change_request.details
p
  strong Urgent:
  = @change_request.urgent

= link_to 'Edit', edit_change_request_path(@change_request)
'  |
= link_to 'Back', change_requests_path

app/views/layouts/_client_nav.html.slim
.nav.nav-tabs
  li.nav-item
    = active_link_to 'Change Requests', change_requests_path, class: 'nav-link'

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 4.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li class='nav-item'><%= link_to 'Edit account', edit_user_registration_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete', class: 'nav-link' %></li>
<% else %>
  <li class='nav-item'><%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li class='nav-item'><%= link_to 'Users', users_path, class: 'nav-link' %></li>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.slim
nav.navbar.navbar-toggleable-md.navbar-light.bg-faded
  button.navbar-toggler.navbar-toggler-right aria-controls="navbarSupportedContent" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarSupportedContent" data-toggle="collapse" type="button" 
    span.navbar-toggler-icon
  a.navbar-brand href="#"  ZDN Enterprises &mdash; Clients
  #navbarSupportedContent.collapse.navbar-collapse
    ul.navbar-nav.mr-auto
      = render 'layouts/navigation_links'
      = render 'layouts/nav_links_for_auth'
    / form.form-inline.my-2.my-lg-0
      input.form-control.mr-sm-2 placeholder="Search" type="text" /
      button.btn.btn-outline-success.my-2.my-sm-0 type="submit"  Search

app/views/layouts/_navigation_links.html.slim
 = link_to 'Home', root_path, class: 'nav-link'

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      / = content_for?(:title) ? yield(:title) : 'Zdne Client'
      = page_title
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Zdne Client'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => 'reload'
    == javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
    == csrf_meta_tags
  body[class="#{body_class}"]
    header
      == render 'layouts/navigation'
      br
      .container
        == render 'layouts/client_nav'      
    main[role="main"]
      == render 'layouts/messages'
      == yield

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>